In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a[1:7]

array([2, 3, 4, 5, 6, 7])

In [9]:
b=a[1:7]
b[::-1]

array([7, 6, 5, 4, 3, 2])

In [10]:
len(a)

10

In [11]:
a.size

10

In [12]:
a.dtype

dtype('int32')

In [13]:
np.sum(a)

55

In [14]:
np.random.rand(4,4)

array([[0.15807349, 0.79954093, 0.87741404, 0.26172247],
       [0.33024836, 0.62649753, 0.11662857, 0.68394578],
       [0.73184782, 0.23352068, 0.63608473, 0.42219364],
       [0.41924852, 0.84767142, 0.85470471, 0.53736794]])

In [15]:
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [25]:
from numpy import random

In [60]:
z = random.randint(size=(10))
z

AttributeError: 'builtin_function_or_method' object has no attribute 'randint'

In [38]:
np.random.rand()

array([], dtype=float64)

In [59]:
from random import random

print(random(), random(), random(), random(), random(), random(), random(), random(), random(), random())

0.7215400323407826 0.22876222127045265 0.9452706955539223 0.9014274576114836 0.030589983033553536 0.0254458609934608 0.5414124727934966 0.9391491627785106 0.38120423768821243 0.21659939713061338


In [53]:
np.random.randint(1,100,10)

array([55, 77,  1, 95, 30, 65, 84, 26, 84, 73])