In [69]:
import numpy as np

height = [1.87, 1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

np_height = np.array(height)
np_weight = np.array(weight)

In [70]:
type(height)

list

In [71]:
type(np_height)

numpy.ndarray

In [72]:
bmi = np_weight/np_height **2
bmi

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [73]:
bmi[bmi>25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [74]:
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# 2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

# 3D Array
arr3= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [75]:
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [76]:
print(arr2)
print(arr2.shape)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [77]:
a = np.array(45)
b = np.array([1, 2, 3, 4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [78]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [80]:
a.ndim

0

In [81]:
b.ndim

1

In [82]:
c.ndim

2

In [83]:
d.ndim

3

In [84]:
arr = np.array([1,2,3,4,5,6])

In [85]:
arr[1]

2

In [86]:
arr[2] + arr[1]

5

In [87]:
c = np.array([[1,2,3],[4,5,6]])

In [88]:
print('2nd element on 1st dim: ', c[0,1])

2nd element on 1st dim:  2


In [89]:
print('3rd element on 2nd dim: ', c[1,2])

3rd element on 2nd dim:  6


In [90]:
arr3= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [91]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
print(arr3[0, 1, 2])

6


In [93]:
print(arr3[1,0,1])

8


In [94]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:5]) #2,3,4
print(arr[4:]) #5,6
print(arr[:4]) #1,2,3,4
print(arr[:-1]) #6,5,4,3,2,1

[2 3 4 5]
[5 6]
[1 2 3 4]
[1 2 3 4 5]


In [95]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [96]:
print(a[1,5])

13


In [97]:
print(a[0, :])

[1 2 3 4 5 6 7]


In [98]:
print(a[:, 0])

[1 8]


In [99]:
#[start:end:stepsize]
print(a[0, 1:-1:2])

[2 4 6]


In [100]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [101]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [102]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
#get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [104]:
#replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [133]:
#All 0s matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [106]:
#All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [107]:
#All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [108]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [109]:
#Any other number (full_like)
np.full_like(a.shape, 4)

array([4, 4])

In [110]:
#Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [137]:
#random decimal numbers
np.random.rand(4,2)

array([[0.89892092, 0.30777623],
       [0.69095725, 0.23069143],
       [0.69830446, 0.67530999],
       [0.13605286, 0.74786833]])

In [135]:
#Random Interger values
np.random.randint(7, size=(3,3))

array([[0, 1, 0],
       [2, 1, 5],
       [3, 3, 6]])

In [113]:
#Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  4,  3],
       [ 3,  1,  6],
       [-2,  1, -1]])

In [139]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [116]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [117]:
a=np.array([1,2,3])
b=a
b[0] = 100

print(a)

[100   2   3]


In [118]:
import pandas as pd

In [119]:
dict = {
    "country": ["Brazil", "Russia", "India", "China", "South Africa"],
    "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
    "area": [8.516, 17.10, 3.286, 9.597, 1.221],
    "population": [200.4, 143.5, 1252, 1357, 52.98]
}

In [120]:
brics = pd.DataFrame(dict)
brics

country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [121]:
brics.index = ["BR", "RU", "IN", "CH", "SA"]
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [122]:
df= pd.read_csv("car-data.csv")
df

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82
5    115        2         8.0    10

In [123]:
df.head(2)

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20

In [124]:
df['speed']

0    200
1     90
2    165
3    110
4    140
5    115
Name: speed, dtype: int64

In [125]:
df[1:4]

speed  car_age  experience  risk
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60

In [126]:
df.iloc[3]

speed         110.0
car_age        20.0
experience      NaN
risk           60.0
Name: 3, dtype: float64

In [127]:
df.loc[[3,5]]

speed  car_age  experience  risk
3    110       20         NaN    60
5    115        2         8.0    10

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   speed       6 non-null      int64  
 1   car_age     6 non-null      int64  
 2   experience  5 non-null      float64
 3   risk        6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 320.0 bytes


In [129]:
df.dropna()

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
4    140        5         3.0    82
5    115        2         8.0    10

In [130]:
df.shape

(6, 4)