In [80]:
import numpy as np

height = [1.87, 1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

np_height = np.array(height)
np_weight = np.array(weight)

In [81]:
type(height)

list

In [82]:
type(np_height)

numpy.ndarray

In [83]:
bmi = np_weight/np_height **2
bmi

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [84]:
bmi[bmi>25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [85]:
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# 2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

# 3D Array
arr3= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [86]:
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [87]:
print(arr2)
print(arr2.shape)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [89]:
a = np.array(45)
b = np.array([1, 2, 3, 4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [73]:
a.ndim

0

In [74]:
b.ndim

1

In [75]:
c.ndim

2

In [76]:
d.ndim

3

In [77]:
arr = np.array([1,2,3,4,5,6])

In [78]:
arr[1]

2

In [79]:
arr[2] + arr[1]

5

In [36]:
c = np.array([[1,2,3],[4,5,6]])

In [40]:
print('2nd element on 1st dim: ', c[0,1])

2nd element on 1st dim:  2


In [42]:
print('3rd element on 2nd dim: ', c[1,2])

3rd element on 2nd dim:  6


In [60]:
arr3= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [61]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
print(arr3[0, 1, 2])

6


In [64]:
print(arr3[1,0,1])

8


In [69]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:5]) #2,3,4
print(arr[4:]) #5,6
print(arr[:4]) #1,2,3,4
print(arr[:-1]) #6,5,4,3,2,1

[2 3 4 5]
[5 6]
[1 2 3 4]
[1 2 3 4 5]
